name: swift-http-types ci
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  #schedule:
    #- cron:  '45 2,13 * * *'
jobs:
  test:
    # emulator fails to launch on ARM macOS with: HVF error: HV_UNSUPPORTED
    #runs-on: macos-15
    # so we need to run on Intel macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package Locally"
        run: swift test
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@v1

